language: node_js
node_js:
  - node
  - 4.4.5

script:
  - npm run build
  - npm test

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: david.p.wood@gmail.com
  api_key:
    secure: IYbz9Dg0VHrf15Ewp3p6LTons+Dn5HTqo0M73uRawrU73GU5ypdXoj+AyqaFhS+QGvOHpKU+sxFTMk6OYZgv4QRMf/T35w47dHJjYLCfyV7JeL4fxY8RVtPWa4ZjrlEgMbWt1i3dkvgStG3cY8MXlZUHvEGv7jShzFOnH4aWyH5fkb7IvNO7AdPuwXhTWqB8U17YqCSlkC1LZ6s27LGl1TneGLYd8azf1Ih4u5jGMHQsZpn5v82F6qBHX5qrJK1MBD2tjcGANkwO+GvFBbKcRCs2IF9Is9ywPKgYNRNamp41MDU1KVszjw7YSpwX4F/iyvWumJgcGGRlOfC6jIGTYord7vM11BrPmowtT+MSpXAOypUOu9WoPb09yHt7d9MEAK6IJatsHtiOxW6EQ5f6K8VKg9Rcle3bL49x61kDIEnSL8hZmf55qclAzWeBQtLg7urxYbtltGG7e5Su56kxi+Gd0B+CR22BZVgMm/38M9ydgbm7hR/3QD54pDt+cxGyTeUU5ua62BCheMnldtB8N5zFwoEg2ZxVwEl++r+QF7Gvst5tXjnxPkAwdE61fDFlFobMfThW8j68QuvmIdNG5wUMEWwtqZ0Ka3AMUbkc/S7AjC0+bjl3qXP5IJJgp2D9EPNX9p/cKFgGKR+AGz16JKfp+0tZ+8P+KKMSj9rHq3g=
  on:
    tags: true
    repo: LiberisLabs/hubot-finbot
