language: node_js
node_js:
  - node
  - 5.11.1

script:
  - npm run build
  - npm test

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: david.p.wood@gmail.com
  api_key:
    secure: IKuAQ6PALgtKkXymSw9pMPetfES+vUL5BB/nfDTvgAFodi5FHEMnSg356+5yJIxo1wQufUExQXimWxNISylr7K4feTZoWloJpaNeQGPUfiCHuu2rJw7ntXhFzzNduIoOTpJHQjYcdaQx1Zi8GrqDWzRXjRDBcrWl0aRA/I+BUelbQT4zKuZAH17vToEtQzZK1Aooucfn9xjjKRfkDtbxRE+lhq8mC094vDv5aDQhHMKGXLgzx0H2727qcErLCPvCPr3IBO08kFL0Xu4easO3E4t2m7VL+em6oSH5DDmFeOQKzxCuWdD3vtmwZgx19YkkuzdVQsx1A3gwlxnPlsvKmQCPvJ+ss6iR5tvRjMjiLk3tuqQKZf80QdqbaM9z7jXFuT2qunl8a36uEe2Vw6R3Y9b6unoQ/cIzHT69kRRtCRKRieEogD7utxMR172+rE79jF6Gb0Fp48B3i9qzl83CEmilPGcKI9upx5r1qSDH03pM0YU8A7J6ey7t8rzAKWoTvaH5KOQtUECDzQPd9atB3J7qMADdyYUfEz0FIY5/QROuFUJXSFwzKdE02rQsxCNzI4wS53assHJ9G1p5sFATIat05jdjVJgt0OEgWkl+aetghYdk6mfjYHzvaxgn9HPhNBi25ic4a0p0/clJBjI7wTa5YY2Fjn8wgQzFnQPn4ds=
  on:
    tags: true
    repo: LiberisLabs/hubot-appveyor
